Step 1: Created Git repository
Step 2: Uploaded local files to Git
Step 3: Configured python application workflow on Git repository
Step 4: Tried to knowingly break a test, but it turned out to not break it
Step 5: Tried breaking a test again, this time it worked
Step 6: Seeing it failed on Git through Python application workflow, I fixed it again.
Step 7: Everything works as it should.